version: '3.8'
services:
  mssql_server:
    container_name: mssql_server
    image: mcr.microsoft.com/azure-sql-edge:latest
    volumes:
      - mssql-azuresql-edge-data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=N@czaaja2537
    ports:
      - "1433:1433"
    networks:
      - web_network
  webserver:
    container_name: frontend_backend_container
    command: sh -c "nginx -g 'daemon on;' && /backend/backend"
    image: naczaaja/golang-angular-todoapp:latest
    ports:
      - "80:80"
      - "8081:8081"
    env_file:
      - backend/.env
    restart: always
    networks:
      - web_network
volumes:
  mssql-azuresql-edge-data:
  db:
    driver: local
  dbmssql:
    driver: local
networks:
  web_network: